package tela.exercicio;

import Ultilizacao.Fase;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

import javax.swing.*;

import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.JOptionPane;


import java.util.Timer;
import java.util.TimerTask;
import tela.TelaMenu;

public class Exercicio extends javax.swing.JFrame {
    //Variveis do relatorio
    String nomeUser;
    int errosTotal, acertoTotal, nivelAtual=0;
    int tempo, letraPorMinuto;
    
    private boolean exeFeito[][] = {
        { false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false
        },
        { false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false
        },
        { false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false
        },
        { false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false
        },
    };
    
    //Dados para serem usados na tela
    Fase faseAtual;
    
    public List<Fase> fases;
    
    
    //Variaveis do Relogio
    private boolean execucaoExercicio = false;
    private boolean rodando = false;
    private Timer tm = new Timer();
    private int contador = 0;
    
    //Variaveis do exercico de Digitação
    private boolean iniciado = false;
    int erros=0, acertos=0, vez=0;
    
    String txtAnterior = ""; //Guarda o estado anterior do texto digitado para infrigir as regras do sistema por exemplo excluir um caractere
    char[] arrayDigitado; //Guada o texto de entrada     
    String txtPraDigitar;
    char[] arrayPraDigitar;
    
    //Cria um StyleContext e um Document para o jtextpane
    StyleContext sc = new StyleContext();
    final DefaultStyledDocument doc = new DefaultStyledDocument(sc);

    // cria um estilo e adiciona atributos personalizados nele
    final javax.swing.text.Style redStyle = sc.addStyle("RED", null);
    final javax.swing.text.Style greenStyle = sc.addStyle("BLUE", null);
    final javax.swing.text.Style defaultStyle = sc.addStyle("WHITE", null);
    
    
    public Exercicio() {
        initComponents();
        nomeUser = TelaMenu.nome;
        nivelAtual = MenuExer.nivel;
        System.out.println(nivelAtual);
        
        fases = new ArrayList<Fase>();
        //Pre
        for(int i=0;i<10;i++){
            exeFeito[nivelAtual][i] = true;
            fases.add(new Fase(nivelAtual, i));
            fases.get(i).setIndex(i);
            fases.get(i).getTxt();
            fases.get(i).setTxt(nivelAtual, i);
            System.out.println(fases.get(i).getTxt());
        }
        
        //Coloca o objeto do array num objeto faseAtual
        faseAtual = fases.get(0);
        
        
        txtSaida.setStyledDocument(doc);
        txtSaida.setEditable(false);
        
        txtEntrada.setEditable(false);
        
        redStyle.addAttribute(StyleConstants.Background, Color.red);
        greenStyle.addAttribute(StyleConstants.Background, Color.green);
        defaultStyle.addAttribute(StyleConstants.Background, Color.WHITE);
        
        this.setTitle("Nivel "+(nivelAtual+1)+ " Exercicio "+faseAtual.getExercicio());
        tituloExercicio.setText("Nivel "+(nivelAtual+1)+ " Exercicio "+faseAtual.getExercicio());
        
        txtEntrada.setAutoscrolls(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        display3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextPane();
        duracao = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        qtdErros = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        qtdAcertos = new javax.swing.JLabel();
        display = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSaida = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        btnReiniciar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnIniciar1 = new javax.swing.JButton();
        tituloExercicio = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        fase1 = new javax.swing.JMenuItem();
        fase2 = new javax.swing.JMenuItem();
        fase3 = new javax.swing.JMenuItem();
        fase4 = new javax.swing.JMenuItem();
        fase5 = new javax.swing.JMenuItem();
        fase6 = new javax.swing.JMenuItem();
        fase7 = new javax.swing.JMenuItem();
        fase8 = new javax.swing.JMenuItem();
        fase9 = new javax.swing.JMenuItem();
        fase10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtEntrada.setAutoscrolls(false);
        txtEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEntradaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntradaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtEntrada);
        txtEntrada.getAccessibleContext().setAccessibleName("");

        duracao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        duracao.setText("- : -");

        label1.setText("Duração");

        label2.setText("Erros");

        qtdErros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtdErros.setText("-");

        label3.setText("Acertos");

        qtdAcertos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtdAcertos.setText("-");

        jScrollPane2.setViewportView(txtSaida);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnReiniciar.setText("REINICIAR");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnIniciar1.setText("PAUSAR");
        btnIniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout display3Layout = new javax.swing.GroupLayout(display3);
        display3.setLayout(display3Layout);
        display3Layout.setHorizontalGroup(
            display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(display3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, display3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdErros, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duracao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
            .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        display3Layout.setVerticalGroup(
            display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(duracao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qtdErros, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(display3Layout.createSequentialGroup()
                        .addGroup(display3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtdAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        label1.getAccessibleContext().setAccessibleDescription("");

        tituloExercicio.setAlignment(java.awt.Label.CENTER);
        tituloExercicio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloExercicio.setText("Titulo do Exercicio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloExercicio, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jMenu1.setText("FASES");

        fase1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        fase1.setText("FASE  1");
        fase1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fase1MouseReleased(evt);
            }
        });
        fase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase1ActionPerformed(evt);
            }
        });
        jMenu1.add(fase1);

        fase2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        fase2.setText("FASE  2");
        fase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase2ActionPerformed(evt);
            }
        });
        jMenu1.add(fase2);

        fase3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        fase3.setText("FASE  3");
        fase3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase3ActionPerformed(evt);
            }
        });
        jMenu1.add(fase3);

        fase4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        fase4.setText("FASE  4");
        fase4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase4ActionPerformed(evt);
            }
        });
        jMenu1.add(fase4);

        fase5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        fase5.setText("FASE  5");
        fase5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase5ActionPerformed(evt);
            }
        });
        jMenu1.add(fase5);

        fase6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        fase6.setText("FASE  6");
        fase6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase6ActionPerformed(evt);
            }
        });
        jMenu1.add(fase6);

        fase7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        fase7.setText("FASE  7");
        fase7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase7ActionPerformed(evt);
            }
        });
        jMenu1.add(fase7);

        fase8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        fase8.setText("FASE  8");
        fase8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase8ActionPerformed(evt);
            }
        });
        jMenu1.add(fase8);

        fase9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        fase9.setText("FASE  9");
        fase9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase9ActionPerformed(evt);
            }
        });
        jMenu1.add(fase9);

        fase10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        fase10.setText("FASE  10");
        fase10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fase10ActionPerformed(evt);
            }
        });
        jMenu1.add(fase10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("AJUDA");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gerarFase(int index){
        iniciado = false;
        execucaoExercicio = false;
        pauseClock();
        txtSaida.setVisible(false);

        //Mapeia os exercios realizados
        exeFeito[fases.get(index).getI()][fases.get(index).getJ()] = true;
        //Coloca o objeto do array num objeto faseAtual
        faseAtual = fases.get(index);
    }
    
    private void txtEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaKeyReleased
        erros = acertos=0;
                
        arrayDigitado = txtEntrada.getText().toCharArray();
        
        //Condição que aciona o metodo de término da atividade
        if(arrayDigitado.length >= arrayPraDigitar.length){
            terminarExercicio();
            txtEntrada.setEditable(false);
        }
            
            
        //Reescreve o exto se ele for mudado
        if(txtAnterior.length() > txtEntrada.getText().length() ||
            txtEntrada.getText().length() > arrayPraDigitar.length
          )txtEntrada.setText(txtAnterior);
        
        //Analisa o texto e printa o resultado
        //O for repete até o numero i for menor que o array digitado e o pra digitar
        for(int i=0;i<arrayDigitado.length && i<arrayPraDigitar.length;i++)
            if(arrayDigitado[i] == arrayPraDigitar[i]){  
            	doc.setCharacterAttributes(i, 1, greenStyle, false);
                //Muda o atriuto de um caractere (No nosso caso ele irá mudar a cor)
                acertos++;
                qtdAcertos.setText(Integer.toString(acertos));
            }else{
                doc.setCharacterAttributes(i, 1, redStyle, false);
                erros++;
                qtdErros.setText(Integer.toString(erros));
            }
            
            txtAnterior = txtEntrada.getText();
    }//GEN-LAST:event_txtEntradaKeyReleased

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MenuExer obj = new MenuExer();
        obj.setVisible(true);
        dispose();        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void fase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase1ActionPerformed
        gerarFase(0);
        preparaExercicio();
    }//GEN-LAST:event_fase1ActionPerformed

    private void fase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase2ActionPerformed
        gerarFase(1);
        preparaExercicio();
    }//GEN-LAST:event_fase2ActionPerformed

    private void txtEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaKeyPressed
        
        //Reescreve o texto se ele for mudado
        if(txtAnterior.length() > txtEntrada.getText().length() ||
            txtEntrada.getText().length() > txtSaida.getText().length()
          )txtEntrada.setText(txtAnterior);
        
        txtAnterior = txtEntrada.getText();
    }//GEN-LAST:event_txtEntradaKeyPressed

    private void txtEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaKeyTyped
        //Reescreve o exto se ele for mudado
        if(txtAnterior.length() > txtEntrada.getText().length() ||
            txtEntrada.getText().length() > txtSaida.getText().length()
          )txtEntrada.setText(txtAnterior);
        
        txtAnterior = txtEntrada.getText();
        //vez++;
        //System.out.println(vez+"º Memoria: "+(txtAnterior.length()+1)+" = Digitado"+(txtEntrada.getText().length()+1));
    }//GEN-LAST:event_txtEntradaKeyTyped

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        
        pauseClock();
        //JOptionPane.showConfirmDialog Para confirmar o reinicio
        if(iniciado)
            if(JOptionPane.showConfirmDialog(null ,"Tem certeza que deseja Reiniciar o Exercício?", "Reiniciar",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                iniciaExercicio();
            else
                startClock();
        else 
            iniciaExercicio();
        
        vez++;
        System.out.println(vez+"º Iniciado: "+iniciado+" Executando: "+execucaoExercicio);
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        if(!iniciado && !execucaoExercicio){
            iniciaExercicio();
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnIniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar1ActionPerformed
        if(iniciado)
        if(execucaoExercicio){
            pausarExercicio();
            btnIniciar1.setText("CONTINUAR");
        }else{
                continuarExercicio();
                btnIniciar1.setText("PAUSAR");       
        }else btnIniciar1.setText("PAUSAR");
        
        vez++;
        System.out.println(vez+"º Iniciado: "+iniciado+" Executando: "+execucaoExercicio+" Rodando: "+rodando);
                   
    }//GEN-LAST:event_btnIniciar1ActionPerformed

    private void fase5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase5ActionPerformed
        gerarFase(4);
        preparaExercicio();
    }//GEN-LAST:event_fase5ActionPerformed

    private void fase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase3ActionPerformed
        gerarFase(2);
        preparaExercicio();
    }//GEN-LAST:event_fase3ActionPerformed

    private void fase4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase4ActionPerformed
        gerarFase(3);
        preparaExercicio();
    }//GEN-LAST:event_fase4ActionPerformed

    private void fase6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase6ActionPerformed
        gerarFase(5);
        preparaExercicio();
    }//GEN-LAST:event_fase6ActionPerformed

    private void fase7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase7ActionPerformed
        gerarFase(6);
        preparaExercicio();
    }//GEN-LAST:event_fase7ActionPerformed

    private void fase8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase8ActionPerformed
        gerarFase(7);
        preparaExercicio();
    }//GEN-LAST:event_fase8ActionPerformed

    private void fase9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase9ActionPerformed
        gerarFase(8);
        preparaExercicio();
    }//GEN-LAST:event_fase9ActionPerformed

    private void fase10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fase10ActionPerformed
        gerarFase(9);
        preparaExercicio();
    }//GEN-LAST:event_fase10ActionPerformed

    private void fase1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fase1MouseReleased
       
    }//GEN-LAST:event_fase1MouseReleased
    
    //Metodo do Iniciar Relógio
    public void startClock(){
        System.out.println("Rodando: "+rodando);
        if(!rodando){
            rodando = true;
            tm = new Timer();
            tm.scheduleAtFixedRate(new TimerTask(){
               @Override
               public void run(){
                   contador++;
                   int seg = contador%60;
                   int min = contador/60;
                   min %= 60;//Pra ficar somente os minutos
                   duracao.setText(String.format("%02d:%02d", min, seg));
               }
            }, 0, 1000);
        }
    }
    
    //Metodo do Iniciar Relogio Relógio
    public void stopClock(){
        if(rodando){
            tm.cancel();
            contador=0;
            rodando = false;
        }
    }
    
    //Metodo do Iniciar Relogio Relógio
    public void pauseClock(){
        if(rodando){
            tm.cancel();
            rodando = false;        
        }
    }
    
    public void preparaExercicio(){
        iniciado = false;
        execucaoExercicio = false;
        
        txtAnterior = "";
        txtEntrada.setText("");

        qtdAcertos.setText(" - ");
        qtdErros.setText(" - ");

        //Reiniciar o tempo
        contador = 0;
        duracao.setText("- : -");
        
        this.setTitle("Nivel "+(nivelAtual+1)+ " Exercicio "+faseAtual.getExercicio());
        tituloExercicio.setText("Nivel "+(nivelAtual+1)+ " Exercicio "+faseAtual.getExercicio());
    }
    
    public void iniciaExercicio(){
        iniciado = true;
        execucaoExercicio = true;
        
        txtSaida.setVisible(true);

        txtAnterior = "";
        txtEntrada.setText("");
        qtdAcertos.setText(" - ");
        qtdErros.setText(" - ");

        //Reiniciar o tempo
        contador = 0;
        duracao.setText("- : -");
        
        
        txtEntrada.setEditable(true);

        txtPraDigitar = faseAtual.getTxt();
        System.out.println(txtPraDigitar);
        arrayPraDigitar = txtPraDigitar.toCharArray(); //Guarda o texto que deve ser digitado
        txtSaida.setText(txtPraDigitar);
        txtEntrada.grabFocus();
        
        startClock();
    }
    
    public void pausarExercicio(){  
        execucaoExercicio = false;
        txtEntrada.setEditable(false);
        pauseClock();
    }
    
    public void continuarExercicio(){
        txtEntrada.setEditable(true);
        txtEntrada.grabFocus();
        execucaoExercicio = true;
        startClock();
    }
    
    public void terminarExercicio(){
        iniciado = false;
        execucaoExercicio = false;
        pauseClock();
        txtSaida.setVisible(false);
        
        jPanel2.setVisible(false);
        
        //errosTotal = Integer.parseInt(qtdErros.getText());
        //acertoTotal = Integer.parseInt(qtdAcertos.getText());
        tempo = contador;
        
        //Aplicação da formula de velocidade de digitação
        //O contador guarda o tempo em segundos
        if(contador<60){
            int k_multiplicador = 60/contador;
            letraPorMinuto = k_multiplicador*arrayPraDigitar.length; 
        }else{  
            letraPorMinuto = arrayPraDigitar.length/contador;
        }

        
        RelatorioExercicio obj = new RelatorioExercicio(nomeUser, qtdErros.getText(), qtdAcertos.getText(),letraPorMinuto, tempo, faseAtual.getNivel(), faseAtual.getExercicio());
        obj.setVisible(true); 
        dispose();
    }
    
    public static void main(String args[]) {        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnIniciar1;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel display;
    private javax.swing.JPanel display3;
    private javax.swing.JLabel duracao;
    private javax.swing.JMenuItem fase1;
    private javax.swing.JMenuItem fase10;
    private javax.swing.JMenuItem fase2;
    private javax.swing.JMenuItem fase3;
    private javax.swing.JMenuItem fase4;
    private javax.swing.JMenuItem fase5;
    private javax.swing.JMenuItem fase6;
    private javax.swing.JMenuItem fase7;
    private javax.swing.JMenuItem fase8;
    private javax.swing.JMenuItem fase9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JLabel qtdAcertos;
    private javax.swing.JLabel qtdErros;
    private java.awt.Label tituloExercicio;
    private javax.swing.JTextPane txtEntrada;
    private javax.swing.JTextPane txtSaida;
    // End of variables declaration//GEN-END:variables
}
