/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela.exercicio;

import tela.TelaMenu;

/**
 *
 * @author jczec
 */
public class MenuExer extends javax.swing.JFrame {

    /**
     * Creates new form MenuExe
     */
    public MenuExer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AMADOR = new javax.swing.JButton();
        MEDIO = new javax.swing.JButton();
        DIFICIL = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        INICIANTE = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1FIM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(510, 479));
        jPanel1.setLayout(null);

        AMADOR.setBackground(new java.awt.Color(0, 0, 0));
        AMADOR.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AMADOR.setForeground(new java.awt.Color(51, 153, 255));
        AMADOR.setText("AMADOR");
        AMADOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMADORActionPerformed(evt);
            }
        });
        jPanel1.add(AMADOR);
        AMADOR.setBounds(104, 143, 395, 57);

        MEDIO.setBackground(new java.awt.Color(0, 0, 0));
        MEDIO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MEDIO.setForeground(new java.awt.Color(51, 153, 255));
        MEDIO.setText("INTERMEDIÁRIO");
        MEDIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEDIOActionPerformed(evt);
            }
        });
        jPanel1.add(MEDIO);
        MEDIO.setBounds(104, 203, 395, 53);

        DIFICIL.setBackground(new java.awt.Color(0, 0, 0));
        DIFICIL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DIFICIL.setForeground(new java.awt.Color(51, 153, 255));
        DIFICIL.setText("PROFISSIONAL");
        DIFICIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIFICILActionPerformed(evt);
            }
        });
        jPanel1.add(DIFICIL);
        DIFICIL.setBounds(104, 262, 395, 60);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 153, 255));
        jButton4.setText("HISTÓRICO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(272, 400, 128, 60);

        INICIANTE.setBackground(new java.awt.Color(0, 0, 0));
        INICIANTE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        INICIANTE.setForeground(new java.awt.Color(51, 153, 255));
        INICIANTE.setText("INICIANTE");
        INICIANTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIANTEActionPerformed(evt);
            }
        });
        jPanel1.add(INICIANTE);
        INICIANTE.setBounds(104, 77, 395, 60);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 153, 255));
        jButton6.setText("AJUDA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(29, 400, 128, 60);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 153, 255));
        jButton7.setText("VOLTAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(492, 400, 128, 60);

        jLabel1FIM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imj/tecladoEXE.png"))); // NOI18N
        jPanel1.add(jLabel1FIM);
        jLabel1FIM.setBounds(-14, -12, 670, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(669, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AMADORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMADORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AMADORActionPerformed

    private void MEDIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEDIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MEDIOActionPerformed

    private void DIFICILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIFICILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DIFICILActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void INICIANTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIANTEActionPerformed
 Exercicio obj = new Exercicio();
     
         obj.setVisible(true);
         
         dispose();

    }//GEN-LAST:event_INICIANTEActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
TelaMenu obj = new TelaMenu();
       
       obj.setVisible(true);
       dispose();

    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuExer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuExer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuExer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuExer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuExer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AMADOR;
    private javax.swing.JButton DIFICIL;
    private javax.swing.JButton INICIANTE;
    private javax.swing.JButton MEDIO;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1FIM;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
